[build]
  # Where your Netlify Functions are located
  functions = "netlify/functions"
  
  # Directory to publish (your root directory)
  publish = "."

# Main redirect rules
[[redirects]]
  from = "/"
  to = "/analytics.html"
  status = 200

[[redirects]]
  from = "/submit-analytics"
  to = "/.netlify/functions/process-analytics"
  status = 200
  force = true

[[redirects]]
  from = "/get-analytics"
  to = "/.netlify/functions/get-analytics"
  status = 200
  force = true

# Security headers (temporarily disabled for testing)
# [[headers]]
#   for = "/analytics.html"
#   [headers.values]
#     X-Frame-Options = "DENY"
#     X-XSS-Protection = "1; mode=block"

# Environment variables
[context.production.environment]
  ANALYTICS_ENABLED = "true"
  
[context.deploy-preview.environment]
  ANALYTICS_ENABLED = "false"