[build]
  command = "npm install && npm run build"
  publish = "dist"
  functions = "netlify/functions"

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["@supabase/supabase-js", "node-fetch"]

[functions.settings]
  timeout = 30

[[redirects]]
  from = "/"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/submit-analytics"
  to = "/.netlify/functions/process-analytics"
  status = 200
  force = true

[[redirects]]
  from = "/get-analytics"
  to = "/.netlify/functions/get-analytics"
  status = 200
  force = true

[context.production.environment]
  SUPABASE_URL = "https://lcxfeysomksslwzhqhwr.supabase.co"
  SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxjeGZleXNvbWtzc2x3emhxaHdyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTIwODgzMzcsImV4cCI6MjA2NzY2NDMzN30.DvD8jfcZLvHdd2Djcd8AJ2wEiutmgkDLBRY5E4Qb3D4"

[[headers]]
  for = "/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET, POST, OPTIONS"
    Access-Control-Allow-Headers = "Content-Type"
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Content-Security-Policy = """
      default-src 'self';
      script-src 'self' https://cdn.jsdelivr.net 'unsafe-inline' 'unsafe-eval';
      style-src 'self' https://cdnjs.cloudflare.com 'unsafe-inline';
      img-src 'self' data: https://*.supabase.co https://your-images-domain.com;
      font-src 'self' https://cdnjs.cloudflare.com;
      connect-src 'self' https://*.supabase.co https://api.ipify.org https://ipapi.co;
      frame-ancestors 'none';
      object-src 'none';
      base-uri 'self';
      form-action 'self';
    """

# Development-specific settings
[context.deploy-preview.environment]
  SUPABASE_URL = "https://lcxfeysomksslwzhqhwr.supabase.co"
  SUPABASE_ANON_KEY = "your-anon-key-here"

[dev]
  framework = "#static"
  targetPort = 3000
  autoLaunch = false