[build]
  functions = "netlify/functions"
  publish = "."

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["node-fetch"]

[[redirects]]
  from = "/"
  to = "/analytics.html"
  status = 200

[[redirects]]
  from = "/submit-analytics"
  to = "/.netlify/functions/process-analytics"
  status = 200
  force = true

[[redirects]]
  from = "/get-analytics"
  to = "/.netlify/functions/get-analytics"
  status = 200
  force = true

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' https://cdn.jsdelivr.net; style-src 'self' 'unsafe-inline'; img-src 'self' data:;"

[context.production.environment]
  ANALYTICS_ENABLED = "true"
  
[context.deploy-preview.environment]
  ANALYTICS_ENABLED = "false"